// <auto-generated />
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20231231225536_ShowNameInSobNPC")]
    partial class ShowNameInSobNPC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Models.GameServer.ApiSobNPC", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxHitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte>("ObjType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("ShowName")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("Sort")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("SobNPCs");
                });
#pragma warning restore 612, 618
        }
    }
}
