// <auto-generated />
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20240101185341_GameMapsChange")]
    partial class GameMapsChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Models.GameServer.ApiFurniture", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ItemID")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("MoneyCost")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Furnitures");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiGameMap", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MapColor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MapDoc")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<ushort>("RebornMap")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("RebornX")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("RebornY")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("RecordSteedRace")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("TypeStatus")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("Uid")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("GameMaps");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiNPC", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxHitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte>("ObjType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("ShowName")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("Sort")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("NPCs");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiSobNPC", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxHitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte>("ObjType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("ShowName")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("Sort")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("SobNPCs");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTrap", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<bool>("AllowDinamic")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TrapID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Traps");
                });
#pragma warning restore 612, 618
        }
    }
}
