// <auto-generated />
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20240114000719_ArenaAndTeamArena")]
    partial class ArenaAndTeamArena
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Models.GameServer.ApiArenaUser", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ArenaPoints")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("CurrentHonor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HistoryHonor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonArenaPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonLose")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonRank")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonWin")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Level")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("Mesh")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<uint>("TodayBattles")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TodayWin")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalLose")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalWin")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("arenas");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiClan", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Allies")
                        .HasColumnType("longtext");

                    b.Property<byte>("BP")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ClanBulletin")
                        .HasColumnType("longtext");

                    b.Property<string>("ClanID")
                        .HasColumnType("longtext");

                    b.Property<uint>("Donation")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Enemies")
                        .HasColumnType("longtext");

                    b.Property<string>("LeaderName")
                        .HasColumnType("longtext");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("clans");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiCrime", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Money")
                        .HasColumnType("int unsigned");

                    b.Property<string>("OwnerName")
                        .HasColumnType("longtext");

                    b.Property<uint>("OwnerUID")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("Crimes");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiFurniture", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ItemID")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("MoneyCost")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Furnitures");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiGameMap", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MapColor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MapDoc")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<ushort>("RebornMap")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("RebornX")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("RebornY")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("RecordSteedRace")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("TypeStatus")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("Uid")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("GameMaps");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiGuild", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("AdvertiseRecruit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Allies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Arsenal")
                        .HasColumnType("longtext");

                    b.Property<uint>("BuletinEnrole")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Bulletin")
                        .HasColumnType("longtext");

                    b.Property<uint>("CTFExploits")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CTFNextConquerPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CTFNextMoney")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CTFRank")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ClaimCtfReward")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ConquerPointFund")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CreateTime")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Enemies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("GuildID")
                        .HasColumnType("int unsigned");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LeaderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("Level")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MembersCount")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MyRank")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Recruit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SilverFund")
                        .HasColumnType("bigint");

                    b.Property<bool>("UseAdvertise")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("guilds");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiNPC", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxHitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte>("ObjType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("ShowName")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("Sort")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("NPCs");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiPortal", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("DestinationMapID")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("DestinationX")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("DestinationY")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("MapID")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Portals");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiSobNPC", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxHitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte>("ObjType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("ShowName")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("Sort")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("SobNPCs");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTeamArenaUser", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ArenaPoints")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("CurrentHonor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HistoryHonor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonArenaPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonLose")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonRank")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonWin")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Level")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("Mesh")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<uint>("TodayBattles")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TodayWin")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalLose")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalWin")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("teamarenas");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTransformation", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("HitPoints")
                        .HasColumnType("smallint unsigned");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<ushort>("SpellID")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("TransformID")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Transformations");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTrap", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<bool>("AllowDinamic")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TrapID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Traps");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTutorBattleLimitType", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("BP")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("SharedBPLimit")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("TutorBattleLimitTypes");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTutorType", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("BattleLevShare")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Index")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxLevel")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MinLevel")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("StudentNum")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("TutorTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
