// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20250318194822_Quests")]
    partial class Quests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API.Models.GameServer.ApiArenaUser", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ArenaPoints")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("CurrentHonor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HistoryHonor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonArenaPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonLose")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonRank")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonWin")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Level")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("Mesh")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<uint>("TodayBattles")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TodayWin")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalLose")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalWin")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("arenas");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiClan", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Allies")
                        .HasColumnType("longtext");

                    b.Property<byte>("BP")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ClanBulletin")
                        .HasColumnType("longtext");

                    b.Property<string>("ClanID")
                        .HasColumnType("longtext");

                    b.Property<uint>("Donation")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Enemies")
                        .HasColumnType("longtext");

                    b.Property<string>("LeaderName")
                        .HasColumnType("longtext");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("clans");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiCrime", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Money")
                        .HasColumnType("int unsigned");

                    b.Property<string>("OwnerName")
                        .HasColumnType("longtext");

                    b.Property<uint>("OwnerUID")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("crimes");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiFurniture", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ItemID")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("MoneyCost")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("furnitures");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiGameMap", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MapColor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MapDoc")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<ushort>("RebornMap")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("RebornX")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("RebornY")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("RecordSteedRace")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("TypeStatus")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("Uid")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("gamemaps");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiGuild", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("AdvertiseRecruit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Allies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Arsenal")
                        .HasColumnType("longtext");

                    b.Property<uint>("BuletinEnrole")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Bulletin")
                        .HasColumnType("longtext");

                    b.Property<uint>("CTFExploits")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CTFNextConquerPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CTFNextMoney")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CTFRank")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ClaimCtfReward")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ConquerPointFund")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("CreateTime")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Enemies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("GuildID")
                        .HasColumnType("int unsigned");

                    b.Property<string>("GuildName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LeaderName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("Level")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MembersCount")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MyRank")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Recruit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SilverFund")
                        .HasColumnType("bigint");

                    b.Property<bool>("UseAdvertise")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("guilds");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiNPC", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxHitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte>("ObjType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("ShowName")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("Sort")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("npcs");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiPlayer", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Agates")
                        .HasColumnType("longtext");

                    b.Property<ushort>("Agility")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("AparenceType")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Archivement")
                        .HasColumnType("longtext");

                    b.Property<uint>("ArenaCPS")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("AtiveQuestApe")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Attributes")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Avatar")
                        .HasColumnType("smallint unsigned");

                    b.Property<byte>("BDExp")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("BanCount")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("BlessTime")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Body")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("BossPoints")
                        .HasColumnType("int");

                    b.Property<int>("BoundConquerPoints")
                        .HasColumnType("int");

                    b.Property<uint>("ChampionPoints")
                        .HasColumnType("int unsigned");

                    b.Property<string>("ChiDragon")
                        .HasColumnType("longtext");

                    b.Property<string>("ChiPhoenix")
                        .HasColumnType("longtext");

                    b.Property<uint>("ChiPoints")
                        .HasColumnType("int unsigned");

                    b.Property<string>("ChiTiger")
                        .HasColumnType("longtext");

                    b.Property<string>("ChiTurtle")
                        .HasColumnType("longtext");

                    b.Property<uint>("ClanDonation")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("ClanRank")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("ClanUID")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("ConquerPoints")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("CountryID")
                        .HasColumnType("smallint unsigned");

                    b.Property<int>("CursedTimer")
                        .HasColumnType("int");

                    b.Property<uint>("DExpTime")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("DailyMonth")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ulong>("DailySignUpDays")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("DailySignUpRewards")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("DailySpiritBeadItem")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<bool>("DbTry")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DemonExterminator")
                        .HasColumnType("longtext");

                    b.Property<uint>("DonationPoints")
                        .HasColumnType("int unsigned");

                    b.Property<int>("DragonPills")
                        .HasColumnType("int");

                    b.Property<string>("EnabledTitles")
                        .HasColumnType("longtext");

                    b.Property<ushort>("Enlighten")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("EnlightenReceive")
                        .HasColumnType("smallint unsigned");

                    b.Property<byte>("ExpBallUsed")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("ExpProtection")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("Experience")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("ExpireVip")
                        .HasColumnType("datetime(6)");

                    b.Property<ushort>("ExtraAttributes")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Face")
                        .HasColumnType("smallint unsigned");

                    b.Property<byte>("FirstClass")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("FirstRebornLevel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Flowers")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FreeVIP")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("FreezeWar")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Get5Out")
                        .HasColumnType("int unsigned");

                    b.Property<int>("GiveFlowersToPerformer")
                        .HasColumnType("int");

                    b.Property<uint>("GuildCPsDonate")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("GuildCTFClaimed")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("GuildCTFConquerPointsReward")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("GuildCTFExploits")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("GuildCTFMoneyReward")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("GuildID")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("GuildLastLogin")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("GuildMoneyDonate")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("GuildPKDonation")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("GuildRank")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Hair")
                        .HasColumnType("smallint unsigned");

                    b.Property<DateTime>("HeavenBlessTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HeavenBlessing")
                        .HasColumnType("int");

                    b.Property<uint>("HistoryChampionPoints")
                        .HasColumnType("int unsigned");

                    b.Property<int>("HitPoints")
                        .HasColumnType("int");

                    b.Property<uint>("HuntingBlessing")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Infection")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("InventorySashCount")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("JailerUID")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("JoinOfflineTG")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("JoinPowerArenaStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("Kungfu")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("LastDragonPill")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("LastMan")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("LotteryEntries")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("MainFlag")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mana")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MiningAttempts")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Money")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("MonsterEntries")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("MonsterEntries2")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("MyFootBallPoints")
                        .HasColumnType("int unsigned");

                    b.Property<string>("MyKillerName")
                        .HasColumnType("longtext");

                    b.Property<uint>("MyKillerUID")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("MysteryFruit")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<ushort>("NameEditCount")
                        .HasColumnType("smallint unsigned");

                    b.Property<ulong>("NobilityDonation")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("NobilityIsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("NobilityLastDonation")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("NobilityPaidRank")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ulong>("NobilityPeriodTime")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("OnlineMinutes")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("OnlinePoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("OnlineTrainingPoints")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("OpenHousePack")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ushort>("PKPoints")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("PMap")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("PMapX")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("PMapY")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("PTB")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("PVEPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("PVPPoints")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Quest2Entries")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Quest3Entries")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("QuestEntries")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("QuizPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("RateExp")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Reborn")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Reincarnation")
                        .HasColumnType("tinyint(1)");

                    b.Property<byte>("RemoveWeapon")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("SSFB")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("SecondClass")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("SecondRebornLevel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("SecurityPass")
                        .HasColumnType("longtext");

                    b.Property<ushort>("Spirit")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Spouse")
                        .HasColumnType("longtext");

                    b.Property<uint>("SpouseUID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Strength")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("SubProfInfo")
                        .HasColumnType("longtext");

                    b.Property<byte>("TCCaptainTimes")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("TheCaptain")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TodayChampionPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalMobsKilled")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalMobsKilled2")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalSouls")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TournamentKills")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TrinityPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("UseChiToken")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("VampireWar")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("VipLevel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("VirtueEntries")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("VirtuePoints")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Vitality")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("VotePoints")
                        .HasColumnType("int unsigned");

                    b.Property<long>("WHMoney")
                        .HasColumnType("bigint");

                    b.Property<uint>("WhackTheThief")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiPortal", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("DestinationMapID")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("DestinationX")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("DestinationY")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("MapID")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("portals");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiQuest", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("IntentionsJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<uint>("PlayerUID")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Status")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Time")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("quests");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiSobNPC", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxHitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte>("ObjType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("ShowName")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("Sort")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("sobnpcs");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiStaticStatue", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxHitPoints")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Mesh")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<byte>("ObjType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("ShowName")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("Sort")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("StatuePackets")
                        .HasColumnType("longtext");

                    b.Property<uint>("StatueSize")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Type")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("static_statues");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTeamArenaUser", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ArenaPoints")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Class")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("CurrentHonor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("HistoryHonor")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonArenaPoints")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonLose")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonRank")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("LastSeasonWin")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("Level")
                        .HasColumnType("smallint unsigned");

                    b.Property<uint>("Mesh")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<uint>("TodayBattles")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TodayWin")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalLose")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TotalWin")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UID")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("teamarenas");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTransformation", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("HitPoints")
                        .HasColumnType("smallint unsigned");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<ushort>("SpellID")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("TransformID")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("transformations");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTrap", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<bool>("AllowDinamic")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Map")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("TrapID")
                        .HasColumnType("int unsigned");

                    b.Property<ushort>("X")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("Y")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.ToTable("traps");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTutorBattleLimitType", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("BP")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("SharedBPLimit")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("tutorbattlelimittypes");
                });

            modelBuilder.Entity("API.Models.GameServer.ApiTutorType", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint>("BattleLevShare")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Index")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaxLevel")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MinLevel")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("StudentNum")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("TutorTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
