namespace API.Models.GameServer
{
    public class Character
    {
        public uint UID { get; set; }
        public ushort Body { get;set; }
        public ushort Face { get; set; }
        public string Name { get; set; }
        public ushort Class { get; set; }
        public uint Map { get; set; }
        public ushort X { get; set; }
        public ushort Y { get; set; }
        public string Spouse { get; set; }
        public ushort FirstClass { get; set; }
        public ushort SecoundClass { get; set; }
        public ushort Avatar { get; set; }
        public uint PMap { get; set; }
        public ushort PMapX { get; set; }
        public ushort PMapY { get; set; }
        public ushort Agility { get; set; }
        public ushort Strength { get; set; }
        public ushort Vitality { get; set; }
        public ushort Spirit { get; set; }
        public uint Atributes { get; set; }
        public ushort Reborn { get; set; }
        public ushort Level { get; set; }
        public uint Hair { get; set; }
        public uint Experience { get; set; }
        public uint MinHitPoints { get; set; }
        public uint MinMana { get; set; }
        public uint ConquerPoints { get; set; }
        public uint BoundConquerPoints { get; set; }
        public uint ArenaCPS { get; set; }
        public uint Money { get; set; }
        public uint MiningAttempts { get; set; }
        public uint VirtutePoints { get; set; }
        public uint VirtuteEntries { get; set; }
        public uint PkPoints { get; set; }
        public uint JailerUID { get; set; }
        public uint QuizPoints { get; set; }
        public uint HelpDesk { get; set; }
        public uint Enilghten { get; set; }
        public uint EnlightenReceive { get; set; }
        public uint DailySignUpDays { get; set; }
        public uint DailyMonth { get; set; }
        public uint DailySignUpRewards { get; set; }
        public uint VipLevel { get; set; }
        public uint VipTime { get; set; }
        public uint LastDragonPill { get; set; }
        public string Achivement { get; set; }
        public uint WHMoney { get; set; }
        public uint TrinityPoints { get; set; }
        public uint BlessTime { get; set; }
        public uint SpouseUID { get; set; }
        public uint HeavenBlessing { get; set; }
        public uint LostTimeBlessing { get; set; }
        public uint HuntingBlessing { get; set; }
        public uint OnlineTrainingPoints { get; set; }
        public uint JoinOfflineTG { get; set; }
        public uint Day { get; set; }
        public uint BDExp { get; set; }
        public uint RateExp { get; set; }
        public uint DExpTime { get; set; }
        public uint ExpBallUsed { get; set; }
        public uint MysteryFruit { get; set; }
        public string SubProfInfo { get; set; }
        public string Dragon { get; set; }
        public string Phoenix { get; set; }
        public string Turtle { get; set; }
        public string Tiger { get; set; }
        public uint ChiPoints { get; set; }
        public string Flowers { get; set; }
        public uint DonationNobility { get; set; }
        public uint FreeVIP { get; set; }
        public uint GuildID { get; set; }
        public uint GuildRank { get; set; }
        public uint FRL { get; set; }
        public uint SRL { get; set; }
        public bool Reincarnation { get; set; }
        public uint LotteryEntries { get; set; }
        public uint QuestEntries { get; set; }
        public uint Quest2Entries { get; set; }
        public uint Quest3Entries { get; set; }
        public uint MonsterEntries { get; set; }
        public uint MonsterEntries2 { get; set; }
        public uint RemoveWeapon { get; set; }
        public bool DbTry { get; set; }
        public string DemonEx { get; set; }
        public uint PkName { get; set; }
        public uint PkUID { get; set; }
        public uint Cursed { get; set; }
        public uint AparienceType { get; set; }
        public uint TKills { get; set; }
        public uint OnlineMinutes { get; set; }
        public uint HistoryChampionPoints { get; set; }
        public uint TodayChampionPoints { get; set; }
        public uint ChampionPoints { get; set; }
        public uint DailySpiritBeadItem { get; set; }
        public string SecurityPass { get; set; }
        public uint TCT { get; set; }
        public uint RacePoints { get; set; }
        public uint LastMan { get; set; }
        public uint PTB { get; set; }
        public uint Get5Out { get; set; }
        public uint FreezeWar { get; set; }
        public uint Infection { get; set; }
        public uint TheCaptain { get; set; }
        public uint Kungfu { get; set; }
        public uint VampireWar { get; set; }
        public uint WhackTheThief { get; set; }
        public uint SSFB { get; set; }
        public uint NameEditCount { get; set; }
        public uint ClaimStateGift { get; set; }
        public uint Enervant { get; set; }
        public uint InventorySashCount { get; set; }
        public uint CountryID { get; set; }
        public uint MyFootBallPoints { get; set; }
        public uint ExpProtection { get; set; }
        public uint BanCount { get; set; }
        public uint ExtraAtributes { get; set; }
        public uint OpenHousePack { get; set; }
        public uint JPAStamp { get; set; }
        public uint GiveFlowersToPerformer { get; set; }
        public uint UseChiToken { get; set; }
        public uint Agates { get; set; }
        public uint OnlinePoints { get; set; }
        public uint PVPPoints { get; set; }
        public uint PVEPoints { get; set; }
        public uint TotalMobsKilled { get; set; }
        public uint TotalMobsKilled2 { get; set; }
        public uint TotalSouls { get; set; }
        public uint DragonPills { get; set; }
        public uint BossPoints { get; set; }
    }
}
